drop table employee if exists;
drop table reservation if exists;
drop table trip if exists;
drop table vehicle if exists;

create table employee (
  id bigint generated by default as identity,
  first_name varchar(255),
  last_name varchar(255),
  svnr varchar(255),
  primary key (id)
);

create table reservation (
  id bigint generated by default as identity,
  date_from timestamp,
  date_to timestamp,
  employee_id bigint,
  vehicle_id bigint,
  primary key (id)
);

create table trip (
  id bigint generated by default as identity,
  start_date timestamp,
  end_date timestamp,
  km_begin double,
  km_end double,
  employee_id bigint,
  vehicle_id bigint,
  primary key (id)
);

create table vehicle (
  id bigint generated by default as identity,
  basic_price double,
  brand varchar(255),
  included_km integer,
  km double,
  model varchar(255),
  number_plate varchar(255),
  penalty_per_day double,
  price_per100km double,
  seat_nr integer,
  vehicle_type varchar(255),
  primary key (id)
);

alter table reservation add constraint fk_reservation_employee
foreign key (employee_id)
references employee;

alter table reservation add constraint fk_reservation_vehicle
foreign key (vehicle_id)
references vehicle;

alter table trip add constraint fk_trip_employee
foreign key (employee_id)
references employee;

alter table trip add constraint fk_trip_vehicle
foreign key (vehicle_id)
references vehicle;
